# product-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: {{.Values.image.repository}}:{{.Values.image.tag}}
          ports:
            - containerPort: 8081
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-secrets  # Or db-config if using ConfigMap
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets  # Or db-config if using ConfigMap
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets  # Or db-config if using ConfigMap
                  key: DB_PASSWORD
            - name: EUREKA_URL
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: eurekaUrl
            - name: APPLICATION_NAME
              value: "productservice"
            - name: SERVER_PORT
              value: "8081"
            - name: JWT_ISSUER
              value: "adena.local"
